### ISSUE TITLE
[Bug] : Test result not associated with our code base/tests are shown against our cycle

### ISSUE THREAD

**Issue by ShampaKumar** [katalon-studio/katalon-testops#177]
For Test results : https://analytics.katalon.com/team/134832/project/149261/executions/200

Test id: https://analytics.katalon.com/team/134832/project/149261/executions/200/test-result/91246085-nach-id  is not part of our test. 
Why is it displayed here. 
Also, this raises a question on data privacy, is any of our results going to be ever exposed to another customer. 
Please sort it out ASAP on high priority. 

Thanks
Shampa

- Katalon Studio Version:
- OS Version:
- Browser Version:

Steps to Reproduce:

1. Test run from Katalon.
2.Check result in analytics

Expected behavior: 
Only tests results of our suite are displayed

Actual behaviour: 
Unrelated test results displayed.

Screenshots:

![image](https://user-images.githubusercontent.com/87659814/126198465-45ee0c94-dcbb-4498-995a-fd48e4f4bf99.png)

**Comment by thongmgnguyen** [comment]
Thank you for your report, we are very appreciated. We fixed it and for your concern, we are applying data security for data protection.

**Comment by ShampaKumar** [comment]
We can still see the incorrect test. The issue is not resolved. 
Also I would like to know the data security steps have been implemented anc confirmed that our organisation data is not shared with any other company. How can I re-open this ticket ?

**Comment by ShampaKumar** [comment]
We can still see the incorrect test. The issue is not resolved.
Also I would like to know the data security steps have been implemented anc confirmed that our organisation data is not shared with any other company. How can I re-open this ticket ?

**Comment by ShampaKumar** [comment]
I still see it in #199
![image](https://user-images.githubusercontent.com/87659814/126294971-60cdfc7f-6833-4c5d-98a6-ce831c52d77c.png)
Can it be removed from all test runs and please confirm what was the resolution and an explaination of what/why it happend and an assurance it won't happen again

**Comment by thongmgnguyen** [comment]
Sorry for your inconvenience, we fixed the issue and are running fixed for old data. Please let me know if this still gets this issue.

**Comment by sangbui** [comment]
Hi @ShampaKumar 

Thanks for your report.

The issue has been resolved immediately after the new code changes and updates. We are evaluating the potential impact that it could have on our users across the TestOps portal with the highest priority.

Thanks again and let us know if you have any questions.
